version: 2.1

orbs:
  node: circleci/node@4.5.0

jobs:
  test-perl:
    docker:
      - image: movabletype/test:trusty
    steps:
      - checkout
      - run:
          name: Test
          command: |
            git clone -b develop --depth 1  https://github.com/movabletype/movabletype.git mt
            cp -r mt/* .
            cp mt/.proverc .
            prove -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/MTBlockEditor/t

  test-js:
    docker:
      - image: cypress/included:7.4.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run cypress:run

  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install build dependency
          command: |
            sudo apt update
            sudo apt --no-install-recommends -y install libjson-perl libyaml-perl
      - run:
          name: Build
          command: |
            perl Makefile.PL --version $(git describe --tags | sed -e 's/^v//')
            make manifest
            make zipdist
            make dist
            mkdir -p packages
            mv MTBlockEditor-* packages
      - run:
          name: Plugins for test
          command: |
            cd plugins/MTBlockEditor/t
            mkdir -p packages
            tar zcf ../../../packages/MTBlockEditorTest.tar.gz plugins
      - store_artifacts:
          path: packages

workflows:
  version: 2
  test_and_build:
    jobs:
      - test-perl
      - test-js
      - build
