version: 2.1

orbs:
  node: circleci/node@4.5.0

commands:
  update-git:
    steps:
      - run: |
          if [ "`cat /etc/redhat-release | sed -e 's/.*\s\([0-9]\)\..*/\1/'`" = 6 ]; then
            yum install http://opensource.wandisco.com/centos/6/git/x86_64/wandisco-git-release-6-1.noarch.rpm -y
            yum install git -y
          fi

jobs:
  test-perl:
    parameters:
      docker-image:
        type: string
        default: movabletype/test:buster
      phpunit:
        type: boolean
        default: true
    docker:
      - image: << parameters.docker-image >>
    steps:
      - update-git
      - checkout
      - run:
          name: Test
          command: |
            git clone -b develop --depth 1 https://github.com/movabletype/movabletype.git mt
            cp -r mt/* .
            cp mt/.proverc .
            # with AdminThemeID=legacy(before admin2023)
            env MT_TEST_ENV_ADMIN_THEME_ID=legacy prove -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/MTBlockEditor/t
            # with AdminThemeID=admin2023
            env MT_TEST_ENV_ADMIN_THEME_ID=admin2023 prove -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/MTBlockEditor/t
            if [ "<< parameters.phpunit >>" = "true" ]; then
              /docker-entrypoint.sh
              phpunit plugins/MTBlockEditor/php
            fi

  test-js:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - node/install-packages
      - run: npm run build-schema
      - run: npm run lint
      - run: npm run format

  test-cypress:
    docker:
      - image: cypress/included:7.4.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run cypress:run

  build:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - run:
          name: Install build dependency
          command: |
            sudo apt update
            sudo apt --no-install-recommends -y install libjson-perl libyaml-perl
      - run:
          name: Build
          command: |
            perl Makefile.PL --version $(git describe --tags | sed -e 's/^v//')
            make manifest
            make zipdist
            make dist
            mkdir -p packages
            mv MTBlockEditor-* packages
      - run:
          name: Plugins for test
          command: |
            cd plugins/MTBlockEditor/t
            mkdir -p packages
            tar zcf ../../../packages/MTBlockEditorTest.tar.gz plugins
      - store_artifacts:
          path: packages

workflows:
  version: 2
  test-and-build:
    jobs:
      - test-perl:
          name: test-perl with buster
          docker-image: movabletype/test:buster
          phpunit: false
      - test-perl:
          name: test-perl with bullseye
          docker-image: movabletype/test:bullseye
      - test-perl:
          name: test-perl with fedora39
          docker-image: movabletype/test:fedora
      - test-perl:
          name: test-perl with fedora40
          docker-image: movabletype/test:fedora40
      - test-perl:
          name: test-perl with fedora41
          docker-image: movabletype/test:fedora41
      - test-perl:
          name: test-perl with cloud7
          docker-image: movabletype/test:cloud7
      - test-js
      - test-cypress
      - build
  tagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
